branch-defaults:
  default:
    environment: image-filter-starter-code-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: image-filter-starter-code
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
